name: Creating Preview Enviorment on Vercel
env:
  VERCEL_ORG_ID: ${{ 'BdynycSfDWufvQAX4vdGGtC4' }}
  VERCEL_PROJECT_ID: ${{ 'prj_VTgQbjjpWvDujuZu3aT49SBrgzL5' }}
on:
  push:
    branches-ignore:
      - master
      - ds
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ '4Bqqd8JrAjYhLaf3hdAcOkjX' }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ '4Bqqd8JrAjYhLaf3hdAcOkjX' }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ '4Bqqd8JrAjYhLaf3hdAcOkjX' }}
