name: Deploying Design System to Vercel
trigger:
  branches:
    include:
      - ds

variables:
  VERCEL_PROJECT_ID: $(PROJECT_ID)
  VERCEL_ORG_ID: $(ORG_ID)
  VERCEL_TOKEN: $(Token)

stages:
  - stage: creating_bundle
    jobs:
      - job: Build
        displayName: Build Storybook
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - script: npm install --global vercel@latest
            displayName: Install Vercel CLI

          - script: vercel pull --yes --environment=production --token=$(VERCEL_TOKEN)
            displayName: Pull Vercel Environment Information

          - script: vercel build --prod --token=$(VERCEL_TOKEN)
            displayName: Build Project Artifacts

          - script: vercel deploy --prebuilt --prod --token=$(VERCEL_TOKEN)
            displayName: Deploy Project Artifacts to Vercel
