name: Creating Preview Enviroment at Vercel

variables:
  VERCEL_PROJECT_ID: $(PROJECT_ID)
  VERCEL_ORG_ID: $(ORG_ID)
  VERCEL_TOKEN: $(Token)

trigger:
  branches:
    exclude:
      - master
      - ds

stages:
  - stage: deploy_preview
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - script: npm install --global vercel@latest
            displayName: Install Vercel CLI

          - script: vercel pull --yes --environment=preview --token=$(VERCEL_TOKEN)
            displayName: Pull Vercel Environment Information

          - script: vercel build --token=$(VERCEL_TOKEN)
            displayName: Build Project Artifacts

          - script: vercel deploy --prebuilt --token=$(VERCEL_TOKEN)
            displayName: Deploy Project Artifacts to Vercel
