name: Platform Production Deployment at Vercel
trigger:
  branches:
    include:
      - master

variables:
  VERCEL_PROJECT_ID: $(PROJECT_ID)
  VERCEL_ORG_ID: $(ORG_ID)
  VERCEL_TOKEN: $(Token)

stages:
  # - stage: Linting
  #   jobs:
  #     - job: linting
  #       displayName: ⬣ ESLint
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - checkout: self
  #           displayName: ⬇️ Checkout repo

  #         - task: NodeTool@0
  #           inputs:
  #             versionSource: 'spec'
  #             versionSpec: '16.x'

  #         - script: npm install
  #           displayName: 📥 Download deps

  #         - script: yarn lint:strict
  #           displayName: 🔬 Lint

  #     - job: TSChecking
  #       displayName: ʦ TypeScript
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - checkout: self
  #           displayName: ⬇️ Checkout repo

  #         - task: NodeTool@0
  #           inputs:
  #             versionSource: 'spec'
  #             versionSpec: '16.x'

  #         - script: npm install
  #           displayName: 📥 Download deps

  #         - script: yarn typecheck
  #           displayName: 🔎 Type check

  #     - job: Prettier
  #       displayName: 💅 Prettier
  #       pool:
  #         vmImage: 'ubuntu-latest'

  #       steps:
  #         - checkout: self
  #           displayName: ⬇️ Checkout repo

  #         - task: NodeTool@0
  #           inputs:
  #             versionSource: 'spec'
  #             versionSpec: '16.x'

  #         - script: npm install
  #           displayName: 📥 Download deps

  #         - script: yarn format:check
  #           displayName: 🔎 Type check

  - stage: Test
    jobs:
      - job: Test
        displayName: 🃏 Testing
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            displayName: ⬇️ Checkout repo

          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: '16.x'

          - script: npm install
            displayName: 📥 Download deps

          - script: yarn test
            displayName: 🃏 Run jest

  - stage: Deploy
    dependsOn: Test
    displayName: ⬣ Deploy to production

    jobs:
      - job: Deploy
        displayName: ⬣ Deploy to production
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            displayName: ⬇️ Checkout repo

          - script: npm install --global vercel@latest
            displayName: ⎔ Setup node/Vercel

          - script: vercel pull --yes --environment=production --token=$(VERCEL_TOKEN)
            displayName: 📥 Pull Vercel Environment Information

          - script: vercel build --prod --token=$(VERCEL_TOKEN)
            displayName: 🔬 Build Project Artifacts

          - script: vercel deploy --prebuilt --prod --token=$(VERCEL_TOKEN)
            displayName: 🃏 Deploy Project to Vercel
