# Workflow name
name: 'Deploying Design System'
env:
  VERCEL_ORG_ID: ${{ 'VERCEL_ORG_ID' }}
  VERCEL_PROJECT_ID: ${{ 'VERCEL_PROJECT_ID' }}

# Event for the workflow
on:
  push:
    branches:
      - ds

# List of jobs
jobs:
  Design-System-Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ 'TOKEN' }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ 'TOKEN' }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ 'TOKEN' }}
