name: Creating Preview Enviorment on Vercel
env:
  VERCEL_ORG_ID: ${{ 'VERCEL_ORG_ID' }}
  VERCEL_PROJECT_ID: ${{ 'VERCEL_PROJECT_ID' }}
on:
  push:
    branches-ignore:
      - master
      - ds
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ 'TOKEN' }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ 'TOKEN' }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ 'TOKEN' }}
